import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: 'belantara-game-edukatif',
    title: 'BELANTARA: Game Edukatif Berbasis Website Interaktif',
    slug: 'belantara-game-edukatif',
    role: 'AI & Web Integration Engineer',
    summary: 'BELANTARA adalah platform edukasi budaya Makassar berbasis website interaktif yang mengintegrasikan Artificial Intelligence (CNN), gamifikasi, dan teknologi imersif.',
    description: `BELANTARA menghadirkan ekosistem pembelajaran budaya digital yang terpadu dengan beberapa fitur utama:

• Fitur Belajar Aksara Lontara: Pengguna dapat mempelajari bentuk huruf, kosakata Bugis-Makassar, serta berlatih menulis di canvas interaktif yang dilengkapi dengan umpan balik otomatis menggunakan AI (CNN).

• Fitur Bermain: Mengandalkan gamifikasi melalui permainan seperti Tebak Gambar, Kuis Aksara Lontara, Teka-Teki Silang, dan Menyusun Kalimat dengan sistem level, poin, coin, dan hati untuk menjaga motivasi dan ritme belajar siswa.

• Fitur Galeri Budaya: Menawarkan eksplorasi digital melalui Virtual Tour dan objek 3D interaktif (seperti pakaian adat dan benda bersejarah) yang terhubung dengan tautan pembelian dari UMKM lokal melalui sistem affiliate commerce.`,
    category: 'Web Development & AI',
    thumbnailUrl: '/project/belantara.png',
    featured: true,
    techStack: ['Phaser.js', 'JavaScript', 'Python', 'Flask', 'TensorFlow', 'CNN', 'MySQL'],
    submissionUrl: 'https://drive.google.com/drive/folders/1sDN6jcgzS39KmQupvzlhrAmN5SUlcTfq?usp=sharing',
    metrics: [
      { label: 'Dataset Model AI', value: '11,000 Gambar' },
      { label: 'Tingkat Daya Tarik', value: '100% Positif' },
      { label: 'Tingkat Keseruan', value: '97% Positif' },
      { label: 'Dampak Edukasi', value: '100% Terbantu' },
    ],
    createdAt: '2025-12-10',
  },
  {
    id: 'ewako-sbm-hr-app',
    title: 'Aplikasi Web HR PT Semen Bosowa Maros (Ewako SBM)',
    slug: 'ewako-sbm-hr-app',
    role: 'Full-Stack Web Developer',
    summary: 'Aplikasi web komprehensif yang dikembangkan untuk mendigitalisasi sistem manajemen sumber daya manusia (SDM) dan mengotomatisasi berbagai proses bisnis inti di Departemen HRGS PT Semen Bosowa Maros.',
    description: 'Proyek ini dirancang sebagai solusi end-to-end untuk menggantikan sistem pelaporan manual yang sebelumnya sangat bergantung pada penggunaan Excel secara intensif. Pengembangan yang dilakukan mencakup perancangan antarmuka pengguna yang intuitif hingga pembangunan arsitektur database yang kuat untuk mengelola data SDM berskala besar secara sistematis. Melalui implementasi teknologi full-stack ini, efisiensi operasional dan akurasi data departemen berhasil ditingkatkan berkat adanya fitur pelaporan otomatis serta visualisasi data secara real-time.',
    category: 'Web Development',
    thumbnailUrl: '/project/bosowa.png',
    featured: true,
    techStack: ['HTML', 'CSS', 'JavaScript', 'CodeIgniter 4', 'Bootstrap'],
    liveUrl: 'https://ewakosbm.id/',
    createdAt: '2025-08-25',
  },
  {
    id: 'anpr-system',
    title: 'Automatic Number Plate Recognition (ANPR)',
    slug: 'anpr-system',
    role: 'Ketua Tim',
    summary: 'Sistem Automatic Number Plate Recognition (ANPR) adalah solusi manajemen parkir yang dibangun dengan pendekatan modular untuk mendeteksi jenis kendaraan, tipe plat, dan membaca karakter plat nomor secara otomatis.',
    description: 'Arsitektur sistem ini menggunakan model client-server di mana frontend menangani interaksi pengguna dan backend mengelola logika bisnis, komunikasi basis data, serta pemrosesan gambar. Alur kerja sistem dimulai dari pengunggahan gambar kendaraan yang diproses menggunakan model YOLO12 untuk mengidentifikasi dan melokalisasi kendaraan serta plat nomor secara akurat. Area plat lalu diekstrak dan dikirimkan ke model AI Gemini untuk diproses menggunakan Optical Character Recognition (OCR) guna membaca teks pada plat nomor Indonesia. Fitur tambahan mencakup perhitungan biaya dan durasi parkir otomatis, verifikasi akses Blacklist/Whitelist, serta dashboard pelaporan pendapatan harian dan kapasitas parkir real-time.',
    category: 'Web Development & AI',
    thumbnailUrl: '/project/anpr.png',
    featured: true,
    techStack: ['Flask', 'FastAPI', 'MySQL', 'XAMPP', 'YOLO12', 'AI Gemini', 'Python', 'Git'],
    submissionUrl: 'https://drive.google.com/drive/folders/1w14gxLH3wkLQ1jmsxPcSUvu_VLGArmbi?usp=sharing',
    metrics: [
      { label: 'Akurasi OCR', value: '> 90%' },
      { label: 'Kecepatan Deteksi', value: '< 3 Detik' },
      { label: 'Integrasi Database', value: '50+ Log Otomatis' },
    ],
    createdAt: '2025-06-10',
  },
  {
    id: 'begal-detector-aiot',
    title: 'Begal-Detector',
    slug: 'begal-detector-aiot',
    role: 'Mobile Developer & AIoT Engineer',
    summary: 'Begal-Detector adalah aplikasi mobile dan sistem keamanan cerdas berbasis AI yang dikembangkan untuk membantu penegak hukum (Bhabinkamtibmas) merespons kejahatan jalanan secara real-time via edge device.',
    description: 'Sistem ini beroperasi menggunakan CCTV yang terintegrasi dengan perangkat edge computing Raspberry Pi 5 dan Hailo AI Kit. Kerangka kerjanya menggabungkan dua model AI: YOLOv8-pose untuk menganalisis gerak tubuh yang mengancam (Human Activity Recognition) dan YOLOv8 untuk mendeteksi keberadaan senjata tajam secara bersamaan. Saat sistem mengenali adanya ancaman (kombinasi gestur mengancam, senjata tajam, dan setidaknya dua orang di dalam bingkai video), sistem akan menangkap bukti video tersebut secara otomatis. Sistem ini juga memiliki aplikasi mobile untuk penegak hukum dengan fitur notifikasi darurat real-time, modul pengenalan wajah (Face Recognition) untuk memverifikasi identitas tersangka, serta integrasi Google Maps untuk navigasi langsung ke lokasi kejadian.',
    category: 'Mobile & AI & IoT',
    thumbnailUrl: '/project/begal.png',
    featured: true,
    techStack: ['Kotlin', 'Python', 'FastAPI', 'YOLOv8', 'Raspberry Pi 5', 'Hailo AI Kit', 'WinSCP & RealVNC', 'Google Maps'],
    paperUrl: 'https://jitce.fti.unand.ac.id/index.php/JITCE/article/view/350/109',
    metrics: [
      { label: 'Kecepatan AI Edge', value: '52.71 FPS' },
      { label: 'Akurasi Deteksi', value: '100% (2m)' },
      { label: 'False Positive', value: '0%' },
      { label: 'Akurasi Malam (IR)', value: '79%' },
    ],
    createdAt: '2025-06-05',
  },
  {
    id: 'nutrisia-mobile-app',
    title: 'Mobile Application: Nutrisia',
    slug: 'nutrisia-mobile-app',
    role: 'Team Leader & Back-End Android Developer',
    summary: 'Nutrisia adalah proyek aplikasi mobile yang dikembangkan sebagai bagian dari kegiatan Project-Based Learning (PBL) di PNUP untuk membantu mencegah obesitas dengan memantau asupan nutrisi harian dan pola makan sehat.',
    description: 'Aplikasi ini memungkinkan pengguna untuk melacak kandungan nutrisi harian dan menerima rekomendasi kesehatan terpersonalisasi. Dilengkapi fitur pemindaian makanan kemasan memanfaatkan teknologi Optical Character Recognition (OCR) untuk mempermudah pemrosesan data nutrisi secara otomatis.',
    category: 'Mobile Development & AI',
    thumbnailUrl: '/project/nutrisia.png',
    featured: true,
    techStack: ['Kotlin', 'PHP', 'REST API', 'OCR', 'GitHub'],
    githubUrl: 'https://github.com/fadilikrm/Nutrisia.git',
    documentationUrl: 'https://youtu.be/jGKfVx5dJ1E?si=oeaEGP6zCZeH-qpr',
    createdAt: '2024-11-15',
  },
  {
    id: 'dokter-panggil-website',
    title: 'Website Dokter Panggil',
    slug: 'dokter-panggil-website',
    role: 'Full Stack Web Developer',
    summary: 'Platform web resmi layanan kesehatan homecare yang dikembangkan secara profesional untuk memfasilitasi pemesanan dokter dan layanan medis langsung ke rumah.',
    description: 'Website ini dirancang secara komersial dan profesional agar responsif, efisien, serta ramah pengguna. Platform ini menghadirkan sistem pemesanan terpadu untuk kunjungan dokter umum maupun spesialis, layanan perawatan luka, infus vitamin, vaksinasi, hingga konsultasi online dan layanan laboratorium. Solusi ini memberikan alternatif layanan kesehatan instan yang aman bagi klien tanpa harus mengunjungi fasilitas kesehatan secara langsung.',
    category: 'Web Development',
    thumbnailUrl: '/project/dokterpanggil.png',
    featured: true,
    techStack: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    liveUrl: 'https://dokterpanggil.id/',
    createdAt: '2023-11-01',
  },
];
