import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: 'nexus-cloud-dashboard',
    title: 'Nexus Platform — Next.js Operations Portal',
    slug: 'nexus-cloud-dashboard',
    summary: 'Platform analitik cloud berkinerja tinggi dengan visualisasi grafik interaktif dan manajemen terpusat.',
    description: 'Nexus Operations Portal adalah aplikasi web berbasis Next.js 15 (App Router) dan Server Components yang digunakan untuk memantau performa layanan dan sistem secara visual. Dilengkapi fitur heatmap latensi, pemantauan real-time via WebSocket, dan ekspor laporan otomatis.',
    category: 'Web Development',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    techStack: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Recharts', 'Zustand'],
    liveUrl: 'https://nexus-demo.fadil.dev',
    githubUrl: 'https://github.com/fadil-dev/nexus-cloud-dashboard',
    metrics: [
      { label: 'Lighthouse Score', value: '98 / 100' },
      { label: 'Bundle Size', value: '< 85 KB' },
      { label: 'Active Users', value: '15,000+' },
    ],
    createdAt: '2025-09-10',
  },
  {
    id: 'pulse-health-tracker',
    title: 'PulseFit Mobile — Personal Health & Fitness App',
    slug: 'pulse-health-tracker',
    summary: 'Aplikasi mobile Android & iOS untuk pelacakan aktivitas fisik harian dan pemantauan statistik kebugaran.',
    description: 'PulseFit Mobile dibangun menggunakan Kotlin dan React Native untuk membantu pengguna melacak statistik kebugaran harian, riwayat latihan, dan metrik kesehatan yang terhubung via Bluetooth Low Energy (BLE).',
    category: 'Mobile Development',
    thumbnailUrl: 'https://images.unsplash.com/photo-1510519138161-58446232811f?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    techStack: ['Kotlin', 'Android SDK', 'React Native', 'TypeScript', 'SQLite', 'Tailwind Native'],
    liveUrl: 'https://pulsefit.fadil.dev',
    githubUrl: 'https://github.com/fadil-dev/pulse-health-tracker',
    metrics: [
      { label: 'App Store Rating', value: '4.9 ★' },
      { label: 'Downloads', value: '50k+' },
      { label: 'Sync Latency', value: '< 200ms' },
    ],
    createdAt: '2025-06-05',
  },
  {
    id: 'vision-sentinel-ai',
    title: 'VisionSentinel AI — Defect Detection System',
    slug: 'vision-sentinel-ai',
    summary: 'Sistem deteksi cacat visual berbasis Computer Vision untuk inspeksi produk di lini perakitan.',
    description: 'VisionSentinel AI dikembangkan untuk mengotomatisasi inspeksi kualitas produk pada lini perakitan. Menggunakan model YOLOv8 yang dioptimasikan dengan TensorRT, sistem ini mampu mendeteksi kerusakan permukaan dengan akurasi tinggi.',
    category: 'AI & Computer Vision',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    techStack: ['Python', 'YOLOv8', 'PyTorch', 'TensorRT', 'OpenCV', 'FastAPI', 'Docker'],
    liveUrl: 'https://demo.visionsentinel.ai',
    githubUrl: 'https://github.com/fadil-dev/vision-sentinel-ai',
    metrics: [
      { label: 'Inference Speed', value: '12ms / frame' },
      { label: 'Accuracy Rate', value: '99.2%' },
      { label: 'Throughput', value: '120 FPS' },
    ],
    createdAt: '2026-01-15',
  },
  {
    id: 'smart-grid-edge-node',
    title: 'SmartGrid Edge IoT — Telemetri Monitoring Daya',
    slug: 'smart-grid-edge-node',
    summary: 'Node IoT berbasis ESP32 dan protokol komunikasi MQTT untuk pemantauan parameter daya terdistribusi.',
    description: 'SmartGrid Edge IoT adalah perangkat pemantauan daya terdistribusi menggunakan mikrokontroler ESP32-S3 dan komunikasi MODBUS RTU. Data daya dikirimkan melalui MQTT ke dashboard analitik.',
    category: 'IoT / Embedded System',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    techStack: ['ESP32', 'FreeRTOS', 'C++', 'MQTT', 'InfluxDB', 'Grafana', 'Modbus'],
    liveUrl: 'https://smartgrid-demo.fadil.dev',
    githubUrl: 'https://github.com/fadil-dev/smart-grid-edge-node',
    metrics: [
      { label: 'Sampling Rate', value: '1 kHz' },
      { label: 'Network Uptime', value: '99.98%' },
      { label: 'Power Draw', value: '0.8W / node' },
    ],
    createdAt: '2025-11-20',
  },
  {
    id: 'agro-eye-crop-analytics',
    title: 'AgroEye — Multispectral Crop Analytics',
    slug: 'agro-eye-crop-analytics',
    summary: 'Analisis vegetasi lahan pertanian menggunakan pengolahan citra dan pemetaan geografis.',
    description: 'AgroEye memanfaatkan citra satelit dan pemrosesan data geospasial untuk menghitung indeks kesehatan tanaman (NDVI) pada lahan pertanian, yang ditampilkan dalam bentuk peta interaktif.',
    category: 'AI & Computer Vision',
    thumbnailUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    featured: false,
    techStack: ['Python', 'PyTorch', 'GDAL', 'Rasterio', 'FastAPI', 'Leaflet', 'PostGIS'],
    liveUrl: 'https://agroeye.fadil.dev',
    githubUrl: 'https://github.com/fadil-dev/agro-eye-crop-analytics',
    metrics: [
      { label: 'Area Covered', value: '250,000 ha' },
      { label: 'Segmentation F1', value: '0.94' },
    ],
    createdAt: '2025-03-12',
  },
];
